title: Portmanteau - music licensing agency.
email: your-email@example.com
description: >-
  Portmanteau is a UK based music licensing agency exclusively representing a range of European record labels, publishers and artists in order to place their music in audio-visual productions around the world. We represent both master and publishing copyrights in most cases and so can clear for use quickly and in 'one-stop'. Our extensive yet select catalogue of labels and publishers is carefully picked in order to offer quality and diversity covering many genres of music with a particular focus on cutting edge, emerging artists and 'buzz' bands.
url: "https://portmanteaumusic.com"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
